---
kind: pipeline
type: docker
name: default

steps:
  - name: app-build
    image: hentioe/elixir:1.17.0-rc.0-otp-27-alpine
    pull: always
    environment:
      MIX_ENV: prod
    commands:
      - mix deps.get
      - mix compile
      - mix release

  - name: image-push
    image: plugins/docker
    settings:
      repo: elixircn/assistant
      username: elixircn
      password:
        from_secret: docker_hub_pass
      dockerfile: Dockerfile
      tags: latest
    when:
      branch:
        - main
      event:
        - push
