---
kind: pipeline
type: docker
name: default

steps:
  - name: app-build
    image: elixircn/elixir:1.14.5-otp-26-slim
    environment:
      MIX_ENV: prod
    commands:
      - apt update && apt install git -y
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix compile
      - mix release

  - name: image-push
    image: plugins/docker
    settings:
      repo: elixircn/assistant
      username: elixircn
      password:
        from_secret: docker_hub_pass
      dockerfile: Dockerfile
      tags: latest
    when:
      branch:
        - master
      event:
        - push
