when:
  - branch: [main]
    event: push

steps:
  app-build:
    image: hentioe/elixir:1.17.3-otp-27-alpine
    pull: true
    environment:
      MIX_ENV: prod
    commands:
      - mix deps.get
      - mix compile
      - mix release

  image-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: elixircn/assistant
      username: elixircn
      password:
        from_secret: elixircn_docker_pass
      dockerfile: Dockerfile

  schedule-deploy:
    image: curlimages/curl
    commands:
      - curl -f -X POST $PRE_DEPLOY_HOOK_URL
    secrets: [PRE_DEPLOY_HOOK_URL]
